#version 460 core
//
layout(local_size_x=128) in;

layout(binding = VISIBILITY_BUFFER_BINDING, std430) restrict writeonly buffer VisibilityDataBuffer {
    uint[] visiblity;
};

layout(binding = LIST_BUFFER_BINDING, std430) restrict readonly buffer SetListBuffer {
    uint[] ids;
};

layout(location=0) uniform uint count;
#define SET_TO uint(-1)
void main() {
    uint id = gl_GlobalInvocationID.x;
    if (count <= id) {
        return;
    }
    visiblity[ids[id]] = SET_TO;
}